import { AspectDefinition } from "./types";

export const framework: AspectDefinition = {
  key: "framework",
  title: "Framework",
  icon: "🧩",
  tagline: "Application framework and structural conventions.",
  scope: ["backend", "frontend", "mobile"],
  cards: [
    {
      id: "framework",
      title: "Application framework",
      fields: [
        {
          id: "framework",
          label: "Framework",
          type: "single",
          options: [
            {
              value: "nextjs",
              label: "Next.js",
              repos: ["frontend", "backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["typescript", "javascript"] }],
            },
            {
              value: "remix",
              label: "Remix / React Router",
              repos: ["frontend", "backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["typescript", "javascript"] }],
            },
            {
              value: "express",
              label: "Express",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["typescript", "javascript"] }],
            },
            {
              value: "nestjs",
              label: "NestJS",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["typescript", "javascript"] }],
            },
            {
              value: "fastify",
              label: "Fastify",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["typescript", "javascript"] }],
            },
            {
              value: "django",
              label: "Django",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["python"] }],
            },
            {
              value: "fastapi",
              label: "FastAPI",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["python"] }],
            },
            {
              value: "rails",
              label: "Ruby on Rails",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["ruby"] }],
            },
            {
              value: "spring-boot",
              label: "Spring Boot",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["java", "kotlin"] }],
            },
            {
              value: "aspnet-core",
              label: "ASP.NET Core",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["csharp"] }],
            },
            {
              value: "laravel",
              label: "Laravel",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["php"] }],
            },
            {
              value: "gin",
              label: "Gin",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["go"] }],
            },
            {
              value: "echo",
              label: "Echo",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["go"] }],
            },
            {
              value: "fiber",
              label: "Fiber",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["go"] }],
            },
            {
              value: "actix-web",
              label: "Actix Web",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["rust"] }],
            },
            {
              value: "axum",
              label: "Axum",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["rust"] }],
            },
            {
              value: "vapor",
              label: "Vapor",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["swift"] }],
            },
            {
              value: "play-framework",
              label: "Play Framework",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["scala"] }],
            },
            {
              value: "phoenix",
              label: "Phoenix",
              repos: ["backend"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["elixir"] }],
            },
            {
              value: "react-native",
              label: "React Native",
              description: "Mobile",
              repos: ["mobile"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["typescript", "javascript"] }],
            },
            {
              value: "flutter",
              label: "Flutter",
              description: "Mobile",
              repos: ["mobile"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["dart"] }],
            },
            {
              value: "swiftui",
              label: "SwiftUI",
              description: "Mobile (iOS native)",
              repos: ["mobile"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["swift"] }],
            },
            {
              value: "jetpack-compose",
              label: "Jetpack Compose",
              description: "Mobile (Android native)",
              repos: ["mobile"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["kotlin", "java"] }],
            },
            {
              value: "maui",
              label: ".NET MAUI",
              description: "Mobile",
              repos: ["mobile"],
              compatibleWhen: [{ aspectKey: "programming-language", fieldId: "language", values: ["csharp"] }],
            },
          ],
        },
        {
          id: "rendering",
          label: "Rendering / architecture style",
          type: "single",
          options: [
            { value: "ssr", label: "Server-rendered (SSR)" },
            { value: "spa", label: "Client-rendered SPA" },
            { value: "static", label: "Static-generated" },
            { value: "hybrid", label: "Hybrid (SSR + client islands)" },
            { value: "api-only", label: "API-only backend, no rendering" },
          ],
        },
      ],
    },
    {
      id: "structure",
      title: "Project structure",
      fields: [
        {
          id: "organization",
          label: "Code organization",
          type: "single",
          options: [
            { value: "feature-based", label: "Feature/domain-based folders" },
            { value: "layer-based", label: "Layer-based folders (controllers/services/models)" },
            { value: "monorepo", label: "Monorepo with multiple packages/apps" },
          ],
        },
        {
          id: "patterns",
          label: "Patterns to adopt",
          type: "multi",
          options: [
            { value: "dependency-injection", label: "Dependency injection" },
            { value: "service-layer", label: "Thin controllers, logic in a service layer" },
            { value: "dto-validation", label: "DTOs / schema validation at every boundary" },
            { value: "colocate-tests", label: "Colocate tests next to source files" },
            { value: "no-business-logic-in-routes", label: "No business logic directly in route handlers" },
          ],
        },
      ],
    },
  ],
};
